# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f178ec7ffcb1f897e103e43487af74aac3c89f712c1d83364454b0252609518e502acfb90c20f8e8a5cad912512aeb41a9a56573a629effeb2f302475cbd2c76

test:
  secret_key_base: 74ac9dfe218a8380a44c3e5aa59a72af55b2381f283622b86303b654d9be84e5ef57dd86406f16a492b36c8660310b1ab446df9e7d47830c2f3fade5d5c163ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
